---
settings:
  name: BlueXP tiering
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: fr-fr,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es
sidebar:
  entries:
  - title: Documents de Tiering BlueXP
    url: "/index.html"
  - title: Notes de mise à jour
    url: "/whats-new.html"
  - title: Commencez
    entries:
    - title: Découvrez le Tiering BlueXP
      url: "/concept-cloud-tiering.html"
    - title: Basculez les données sur site dans le cloud
      entries:
      - title: Tiering dans Amazon S3
        url: "/task-tiering-onprem-aws.html"
      - title: Tiering dans le stockage Azure Blob
        url: "/task-tiering-onprem-azure.html"
      - title: Tiering dans Google Cloud Storage
        url: "/task-tiering-onprem-gcp.html"
      - title: Tiering dans StorageGRID
        url: "/task-tiering-onprem-storagegrid.html"
      - title: Tiering dans le stockage objet S3
        url: "/task-tiering-onprem-s3-compat.html"
    - title: Configuration des licences
      url: "/task-licensing-cloud-tiering.html"
    - title: FAQ
      url: "/faq-cloud-tiering.html"
  - title: Utilisez le Tiering BlueXP
    entries:
    - title: Gérer le Tiering des données
      url: "/task-managing-tiering.html"
    - title: Gérer le stockage objet
      url: "/task-managing-object-storage.html"
    - title: Tester les performances cloud
      url: "/task-tiering-test.html"
    - title: Afficher la présentation de Tiering pour tous les clusters
      url: "/task-tiering-onprem-overview.html"
  - title: Référence
    entries:
    - title: Classes et régions de stockage Amazon S3 prises en charge
      url: "/reference-aws-support.html"
    - title: Régions et tiers d'accès Azure pris en charge
      url: "/reference-azure-support.html"
    - title: Classes et régions de stockage Google Cloud prises en charge
      url: "/reference-google-support.html"
  - title: Connaissances et support
    entries:
    - title: S'inscrire pour obtenir de l'aide
      url: "/task-support-registration.html"
    - title: Obtenez de l'aide
      url: "/task-get-help.html"
  - title: Mentions légales
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Commencez
    links:
    - title: Découvrez le Tiering BlueXP
      url: concept-cloud-tiering.html
    - title: Nouveautés
      url: whats-new.html
    - title: Configuration des licences
      url: task-licensing-cloud-tiering.html
  - title: Déplacez les données ONTAP sur site vers le cloud
    links:
    - title: Tiering dans Amazon S3
      url: task-tiering-onprem-aws.html
    - title: Tiering dans Azure Blob
      url: task-tiering-onprem-azure.html
    - title: Tiering dans Google Cloud
      url: task-tiering-onprem-gcp.html
    - title: Tiering dans StorageGRID
      url: task-tiering-onprem-storagegrid.html
    - title: Tiering dans le système S3 générique
      url: task-tiering-onprem-s3-compat.html
  - title: Gérer les paramètres de Tiering
    links:
    - title: Modifier la règle de Tiering d'un volume
      url: task-managing-tiering.html#changing-a-volumes-tiering-policy
    - title: Révision des informations de hiérarchisation pour un cluster
      url: task-managing-tiering.html#reviewing-tiering-info-for-a-cluster
    - title: Procéder au Tiering des données à partir de volumes supplémentaires
      url: task-managing-tiering.html#tiering-data-from-additional-volumes
    - title: Déplacez les données du cloud vers le Tier de performance
      url: task-managing-tiering.html#migrating-data-from-the-cloud-tier-back-to-the-performance-tier
    - title: Gestion des paramètres de Tiering sur les agrégats
      url: task-managing-tiering.html#managing-tiering-settings-on-aggregates
  - title: Gérer le stockage objet
    links:
    - title: Ajoutez un nouveau magasin d'objets pour un cluster
      url: task-managing-object-storage.html#adding-a-new-object-store
    - title: Ajoutez un second magasin d'objets à un agrégat pour la mise en miroir
      url: task-managing-object-storage.html#attaching-a-second-object-store-to-an-aggregate-for-mirroring
    - title: Intervertir le magasin d'objets principal et miroir
      url: task-managing-object-storage.html#swapping-the-primary-and-mirror-object-store
    - title: Supprime un magasin d'objets symétriques
      url: task-managing-object-storage.html#removing-a-mirror-object-store-from-an-aggregate
  - title: Communauté sur les blogs
    links:
    - title: Communauté NetApp
      url: https://community.netapp.com/t5/BlueXP-and-Services/ct-p/CDS
    - title: Blog sur le Tiering BlueXP
      url: https://bluexp.netapp.com/blog/topic/cloud-tiering
    - title: Webinaires sur le cloud
      url: https://bluexp.netapp.com/events
  - title: Autres ressources
    links:
    - title: Cas d'utilisation de BlueXP
      url: https://bluexp.netapp.com/cloud-tiering
product-family:
  name: BlueXP
  repo: cloud-manager-family
  sidebar_label: Toute la documentation BlueXP
