---
settings:
  name: BlueXP tiering
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: fr-fr,us-en,de-de,es-es,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documents de Tiering BlueXP
    url: "/index.html"
  - title: Notes de mise à jour
    url: "/whats-new.html"
  - title: Commencez
    entries:
    - title: Découvrez le Tiering BlueXP
      url: "/concept-cloud-tiering.html"
    - title: Transférer les données sur site vers le cloud
      entries:
      - title: Tiering dans Amazon S3
        url: "/task-tiering-onprem-aws.html"
      - title: Tiering dans le stockage Azure Blob
        url: "/task-tiering-onprem-azure.html"
      - title: Tiering dans Google Cloud Storage
        url: "/task-tiering-onprem-gcp.html"
      - title: Tiering dans StorageGRID
        url: "/task-tiering-onprem-storagegrid.html"
      - title: Tiering dans le stockage objet S3
        url: "/task-tiering-onprem-s3-compat.html"
    - title: Configuration des licences
      url: "/task-licensing-cloud-tiering.html"
    - title: FAQ
      url: "/faq-cloud-tiering.html"
  - title: Utilisez le Tiering BlueXP
    entries:
    - title: Gérer le Tiering des données
      url: "/task-managing-tiering.html"
    - title: Gérer le stockage objet
      url: "/task-managing-object-storage.html"
    - title: Tester les performances cloud
      url: "/task-tiering-test.html"
    - title: Afficher la présentation de Tiering pour tous les clusters
      url: "/task-tiering-onprem-overview.html"
    - title: Surveillez l'état des alertes de hiérarchisation
      url: "/task-monitor-tiering-alerts.html"
  - title: Référence
    entries:
    - title: Classes et régions de stockage Amazon S3 prises en charge
      url: "/reference-aws-support.html"
    - title: Régions et tiers d'accès Azure pris en charge
      url: "/reference-azure-support.html"
    - title: Classes et régions de stockage Google Cloud prises en charge
      url: "/reference-google-support.html"
  - title: Connaissances et support
    entries:
    - title: S'inscrire pour obtenir de l'aide
      url: "/task-support-registration.html"
    - title: Obtenez de l'aide
      url: "/task-get-help.html"
  - title: Mentions légales
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
