---
sidebar: sidebar 
permalink: reference-azure-support.html 
keywords: microsoft azure, azure, hot, access tier, cold, regions 
summary: 'Le Tiering BlueXP prend en charge deux tiers d"accès et la plupart des régions.' 
---
= Tiers et régions d'accès Azure Blob pris en charge
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le Tiering BlueXP prend en charge deux tiers d'accès et la plupart des régions.



== Tiers d'accès Azure Blob pris en charge

Lorsque vous configurez le Tiering des données dans Azure à partir de vos systèmes ONTAP sur site, le Tiering BlueXP utilise automatiquement le Tier d'accès _Hot_ pour vos données inactives. Le Tiering BlueXP peut appliquer une règle de cycle de vie afin que les données puissent passer du niveau d'accès _Hot_ au niveau d'accès _Cool_ au bout d'un certain nombre de jours.

Si vous ne choisissez pas le niveau d'accès _Cool_, les données restent dans le niveau d'accès _Hot_ et aucune règle n'est appliquée.

Lorsque vous configurez une règle de cycle de vie de Tiering BlueXP, vous ne devez pas configurer de règles de cycle de vie lors de la configuration du conteneur dans votre compte Azure.

https://docs.microsoft.com/en-us/azure/storage/blobs/access-tiers-overview["Découvrez les niveaux d'accès d'Azure Blob"^].



== Régions Azure prises en charge

Le Tiering BlueXP prend en charge le Tiering vers n'importe quel compte de stockage, dans n'importe quelle région, accessible via le connecteur.
