---
sidebar: sidebar 
permalink: reference-azure-support.html 
keywords: microsoft azure, azure, hot, access tier, cold, regions 
summary: 'Le Tiering BlueXP prend en charge deux tiers d"accès et la plupart des régions.' 
---
= Tiers et régions d'accès Azure Blob pris en charge
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le Tiering BlueXP prend en charge deux tiers d'accès et la plupart des régions.



== Tiers d'accès Azure Blob pris en charge

Lorsque vous configurez le Tiering des données dans Azure à partir de vos systèmes ONTAP sur site, le Tiering BlueXP utilise automatiquement le Tier d'accès _Hot_ pour vos données inactives. Le Tiering BlueXP peut appliquer une règle de cycle de vie afin que les données puissent passer du niveau d'accès _Hot_ au niveau d'accès _Cool_ au bout d'un certain nombre de jours.

Si vous ne choisissez pas le niveau d'accès _Cool_, les données restent dans le niveau d'accès _Hot_ et aucune règle n'est appliquée.

Lorsque vous configurez une règle de cycle de vie de Tiering BlueXP, vous ne devez pas configurer de règles de cycle de vie lors de la configuration du conteneur dans votre compte Azure.

https://docs.microsoft.com/en-us/azure/storage/blobs/access-tiers-overview["Découvrez les niveaux d'accès d'Azure Blob"^].



== Régions Azure prises en charge

Le Tiering BlueXP  prend en charge plusieurs régions Azure. Les régions Azure Chine ne sont pas prises en charge en tant que destinations de Tiering.



=== Afrique

* Afrique du Sud Nord




=== Asie Pacifique

* Australie Est
* Australie Sud-Est
* Asie de l'Est
* Japon Est
* Japon Ouest
* Corée Centrale
* Corée du Sud
* Asie du Sud-Est




=== Europe

* France centrale
* Allemagne de l'ouest du centre
* Allemagne du Nord
* Europe du Nord
* Royaume-Uni Sud
* Royaume-Uni Ouest
* Europe de l'Ouest




=== Amérique du Nord

* Canada Central
* Canada Est
* Centre DES ÉTATS-UNIS
* Est-É.-U.
* Est DES ÉTATS-UNIS 2
* Centre-nord des États-Unis
* Centre-sud des États-Unis
* Ouest des États-Unis
* Ouest des États-Unis 2
* Centre Ouest des États-Unis




=== Amérique du Sud

* Brésil Sud

